
# Make necessary imports 


In [9]:

import pandas as pd
from sklearn.model_selection import train_test_split, RandomizedSearchCV, cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report
from sklearn.feature_selection import f_classif, SelectKBest
from sklearn.preprocessing import LabelEncoder
import matplotlib.pyplot as plt
from sklearn.inspection import permutation_importance
from collections import Counter
import numpy as np
from scipy.stats import randint

# Train Data

In [7]:
df= pd.read_csv('traindata5thproject')

In [17]:
df.shape

(1499197, 29)

# Splitting data

In [11]:

X= df.drop('IncidentGrade',axis=1)
y= df['IncidentGrade']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Logistic Regression 

In [13]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

# Split the data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize the Logistic Regression model
clf = LogisticRegression(max_iter=1000)

# Fit the model
clf.fit(X_train, y_train)

# Make predictions
classification_predictions = clf.predict(X_test)

# Calculate evaluation metrics
accuracy = accuracy_score(y_test, classification_predictions)
precision = precision_score(y_test, classification_predictions, average='macro')
recall = recall_score(y_test, classification_predictions, average='macro')
f1 = f1_score(y_test, classification_predictions, average='macro')
conf_matrix = confusion_matrix(y_test, classification_predictions)

# Print the evaluation metrics
print("Accuracy:", accuracy)
print("Precision (Macro):", precision)
print("Recall (Macro):", recall)
print("F1 Score (Macro):", f1)
print("Confusion Matrix:\n", conf_matrix)


Accuracy: 0.39873932764140874
Precision (Macro): 0.39000211673292134
Recall (Macro): 0.39883548121107476
F1 Score (Macro): 0.38465537713784764
Confusion Matrix:
 [[45796 21846 31711]
 [38963 20160 41041]
 [31351 15370 53602]]


# Decision Tree Classifier

In [14]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

# Split the data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize the Decision Tree Classifier model
classifier = DecisionTreeClassifier(random_state=42)

# Fit the model
classifier.fit(X_train, y_train)

# Make predictions
classification_predictions = classifier.predict(X_test)

# Calculate evaluation metrics
accuracy = accuracy_score(y_test, classification_predictions)
precision = precision_score(y_test, classification_predictions, average='macro')
recall = recall_score(y_test, classification_predictions, average='macro')
f1 = f1_score(y_test, classification_predictions, average='macro')
conf_matrix = confusion_matrix(y_test, classification_predictions)

# Print the evaluation metrics
print("Accuracy:", accuracy)
print("Precision (Macro):", precision)
print("Recall (Macro):", recall)
print("F1 Score (Macro):", f1)
print("Confusion Matrix:\n", conf_matrix)


Accuracy: 0.9761572838847385
Precision (Macro): 0.9761602405100237
Recall (Macro): 0.9761514882558298
F1 Score (Macro): 0.9761548359586323
Confusion Matrix:
 [[96804  1447  1102]
 [ 1298 97785  1081]
 [ 1021  1200 98102]]


# Random Forest Classifier model


In [12]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

# Split the data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize the Random Forest Classifier model
rf_clf = RandomForestClassifier(n_estimators=100, random_state=42)

# Fit the model
rf_clf.fit(X_train, y_train)

# Make predictions
classification_predictions = rf_clf.predict(X_test)

# Calculate evaluation metrics
accuracy = accuracy_score(y_test, classification_predictions)
precision = precision_score(y_test, classification_predictions, average='macro')
recall = recall_score(y_test, classification_predictions, average='macro')
f1 = f1_score(y_test, classification_predictions, average='macro')
conf_matrix = confusion_matrix(y_test, classification_predictions)


# Print the evaluation metrics
print("Accuracy:", accuracy)
print("Precision (Macro):", precision)
print("Recall (Macro):", recall)
print("F1 Score (Macro):", f1)
print("Confusion Matrix:\n", conf_matrix)


Accuracy: 0.9637940234791889
Precision (Macro): 0.9639275250897631
Recall (Macro): 0.9638028983310157
F1 Score (Macro): 0.9637977331561635
Confusion Matrix:
 [[95916  2242  1195]
 [ 1987 97235   942]
 [ 2680  1810 95833]]


# Gradient Boosting Classifier

In [15]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

# Split the data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize the Gradient Boosting Classifier model
gb_clf = GradientBoostingClassifier(n_estimators=100, random_state=42)

# Fit the model
gb_clf.fit(X_train, y_train)

# Make predictions
classification_predictions = gb_clf.predict(X_test)

# Calculate evaluation metrics
accuracy = accuracy_score(y_test, classification_predictions)
precision = precision_score(y_test, classification_predictions, average='macro')
recall = recall_score(y_test, classification_predictions, average='macro')
f1 = f1_score(y_test, classification_predictions, average='macro')
conf_matrix = confusion_matrix(y_test, classification_predictions)

# Print the evaluation metrics
print("Accuracy:", accuracy)
print("Precision (Macro):", precision)
print("Recall (Macro):", recall)
print("F1 Score (Macro):", f1)
print("Confusion Matrix:\n", conf_matrix)


Accuracy: 0.7975153415154749
Precision (Macro): 0.8099176894476772
Recall (Macro): 0.7977233930254871
F1 Score (Macro): 0.7986627712721109
Confusion Matrix:
 [[85883 10079  3391]
 [17423 78444  4297]
 [17314  8209 74800]]


# Test Data

In [18]:
df_test= pd.read_csv('testdata5thproject')

In [19]:
df_test

Id  OrgId  IncidentId  AlertId  DetectorId  AlertTitle  \
0        1005022347995    120      121132   112263          84       14893   
1        1254130455382    152        3989     2642         232         211   
2        1683627184909    152       83762   946238           0           0   
3         317827581215     44        1567    15495          50          36   
4         910533067991    215       35612    68280           1           1   
...                ...    ...         ...      ...         ...         ...   
1499980   231928234560     93          10        0          27          18   
1499981   395136994352     73      576373  1612333          80      102778   
1499982    68719479735    124       26628   339587           9          64   
1499983   146028892595    105       30381   119594           6           5   
1499984   627065227412    613         959   269983         534         582   

         Category  IncidentGrade  EntityType  EvidenceRole  ...  \
0               7              0          14             0  ...   
1               2              0          11             1  ...   
2              10              0          11             1  ...   
3               7              0          14             0  ...   
4              10              0          13             1  ...   
...           ...            ...         ...           ...  ...   
1499980         5              1          25             0  ...   
1499981         7              1          25             0  ...   
1499982         6              1           4             0  ...   
1499983        10              1          25             0  ...   
1499984         4              1          20             1  ...   

         RegistryValueName  ApplicationId  OAuthApplicationId  ResourceIdName  \
0                      635           2251                 881            3586   
1                      635           2251                 881            3586   
2                      635           2251                 881            3586   
3                      635           2251                 881            3586   
4                      635           2251                 881            3586   
...                    ...            ...                 ...             ...   
1499980                635           2251                 881            3586   
1499981                635           2251                 881            3586   
1499982                635              2                 881            3586   
1499983                635           2251                 881            3586   
1499984                635           2251                 881            3586   

         OSFamily  CountryCode  Day  Month  Hour  Week  
0               5          242    5      6    21    23  
1               5          242    9      6    23    23  
2               5            4   11      6    10    24  
3               5          242   15      6     8    24  
4               5          242   15      6    21    24  
...           ...          ...  ...    ...   ...   ...  
1499980         5          242   11      6    22    24  
1499981         5          242    4      6     8    23  
1499982         5          242    6      6     5    23  
1499983         5          242   12      6     0    24  
1499984         5          242   15      6     0    24  

[1499985 rows x 29 columns]

# Splitting data

In [20]:

X= df_test.drop('IncidentGrade',axis=1)
y= df_test['IncidentGrade']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [21]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

# Split the data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize the Decision Tree Classifier model
classifier = DecisionTreeClassifier(random_state=42)

# Fit the model
classifier.fit(X_train, y_train)

# Make predictions
classification_predictions = classifier.predict(X_test)

# Calculate evaluation metrics
accuracy = accuracy_score(y_test, classification_predictions)
precision = precision_score(y_test, classification_predictions, average='macro')
recall = recall_score(y_test, classification_predictions, average='macro')
f1 = f1_score(y_test, classification_predictions, average='macro')
conf_matrix = confusion_matrix(y_test, classification_predictions)

# Print the evaluation metrics
print("Accuracy:", accuracy)
print("Precision (Macro):", precision)
print("Recall (Macro):", recall)
print("F1 Score (Macro):", f1)
print("Confusion Matrix:\n", conf_matrix)


Accuracy: 0.985059850598506
Precision (Macro): 0.9850647223081612
Recall (Macro): 0.9850526777025671
F1 Score (Macro): 0.9850561138230766
Confusion Matrix:
 [[97659  1020   708]
 [  738 98961   554]
 [  732   730 98895]]
